---
swagger: "2.0"
info:
  description: "This is the API spec of the interstellar route planner"
  version: "1.0.0"
  title: "The interstellar route planner"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "transport"
  description: "For all your transport needs to the nearest star"
- name: "gates"
  description: "If you wish to make trips between our gates"
schemes:
- "https"

paths:
  /transport/{distance}:
    get:
      tags:
      - "transport"
      summary: "returns the cheapest vehicle to use (and the cost of the journey) for the given distance (in AUs), number of passengers and days of parking (i.e. vehicle storage at the gate)"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: distance
          schema:
            type: float
          required: true
          description: numeric ID of the user to get
        - in: query
          name: passengers
          schema:
            type: integer
          required: true
          description: the number of apssengers wishing to travel
        - in: query
          name: parking
          schema:
            type: integer
          required: true
          description: the number of days for which the vehicle needs to be parked
      
      responses:
        200:
          description: the prices have successfully been calculated
          schema:
            type: object
            properties:
              personalTransportCost:
                type: number
              hstcTransportCost:
                type: number
              lowestTransportCost:
                type: number
        400:
          description: the input parameters are missing or incorrectly formatted

  /gates:
    get:
      tags:
      - "gates"
      summary: "returns the list of all gates with their information"
      produces:
      - "application/json"
      responses:
        200:
          description: the information on all gates
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                connections:
                  type: array
                  items:
                    type: object
                    properties:
                      hu:
                        type: integer
                      id:
                        type: string

  /gates/{gateCode}:
    get:
      tags:
      - "gates"
      summary: "returns the information on the gate specified"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: gateCode
          schema:
            type: string
          required: true
          description: the code of the gate on which the information is required, a three letter string such as 'ALT'
      responses:
        200:
          description: the information on the gate
          schema:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              connections:
                type: array
                items:
                  type: object
                  properties:
                    hu:
                      type: integer
                    id:
                      type: string
        400:
          description: the gate specified does not exist
  
  /gates/{gateCode}/to/{targetGateCode}:
    get:
      tags:
      - "gates"
      summary: "returns the distance of the two gates, optionally in both ways"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: gateCode
          schema:
            type: string
          required: true
          description: the gate code of the start gate
        - in: path
          name: targetGateCode
          schema:
            type: string
          required: true
          description: the gate code of the destination gate
        - in: query
          name: round_trip
          schema:
            type: boolean
          description: whether the return trip distance is required
      responses:
        200:
          description: the information on the gate
          schema:
            anyOf:
              - $ref: "#/definitions/OneWayJourneyLength"
              - $ref: "#/definitions/ReturnJourneyLength"
        400:
          description: one or more gate codes are incorrect

definitions:
  OneWayJourneyLength:
    type: object
    properties:
      outboundDistance:
        type: integer
  ReturnJourneyLength:
    type: object
    properties:
      outboundDistance:
        type: integer
      returnDistance:
        type: integer


  


