---
swagger: "2.0"
info:
  description: "This is the API spec of the interstellar route planner"
  version: "1.0.0"
  title: "The interstellar route planner"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "transport"
  description: "For all your transport needs to the nearest star"
- name: "gates"
  description: "If you wish to make trips between our gates"
schemes:
- "https"

paths:
  /transport/{distance}:
    get:
      tags:
      - "transport"
      summary: "returns the cheapest vehicle to use (and the cost of the journey) for the given distance (in AUs), number of passengers and days of parking (i.e. vehicle storage at the gate)"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: distance
          schema:
            type: float
          required: true
          description: Numeric ID of the user to get
        - in: query
          name: passengers
          schema:
            type: integer
          required: true
          description: The number of apssengers wishing to travel
        - in: query
          name: parking
          schema:
            type: integer
          required: true
          description: The number of days for which the vehicle needs to be parked
      
      responses:
        200:
          description: the prices have successfully been calculated
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalTransportCost:
                    type: number
                    description: The user ID.
                  hstcTransportCost:
                    type: number
                    description: The user name.
                  lowestTransportCost:
                    type: number
                    description: The user name.
        400:
          description: the input parameters are missing or incorrectly formatted
